#goal definition
# TODO: replace boardstate with Drill custom msg
Session drill
---
#result definition
# DrillStats stats
Statistics final_state
---
#feedback
#TODO: find something useful to return as feedback, status of board?
Statistics current_state
